<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>lilishop-all</artifactId>
    <parent>
        <groupId>cn.lili</groupId>
        <artifactId>lili-shop-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <dependencies>
        <dependency>
            <groupId>cn.lili</groupId>
            <artifactId>framework</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.lili</groupId>
            <artifactId>common-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.lili</groupId>
            <artifactId>buyer-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.lili</groupId>
            <artifactId>seller-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.lili</groupId>
            <artifactId>manager-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.lili</groupId>
            <artifactId>im-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.lili</groupId>
            <artifactId>consumer</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.jfinal</groupId>
            <artifactId>enjoy</artifactId>
            <version>${enjoy.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>cn.lili.LilishopApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
